config/routes.rb
Rails.application.routes.draw do
  resources :switches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/button', to: 'switches#button`, as: 'button`
  get '/toggle' => "switches#toggle", as: 'toggle'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/switch.rb
class Switch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/switches_controller.rb
class SwitchesController < ApplicationController
  include SetupSwitches
  before_action :setup_switches

  def index
    @switches = Switch.all
  end

  def show
    @switch = Switch.find(params[:id])
  end

  def edit
    @switch = Switch.find(params[:id])
    Wemote::Switch.find(@switch.name).toggle!
    redirect_to @switch
  end

  def toggle
    @switch = Switch.find(params[:switch])
    Wemote::Switch.find(@switch.name).toggle!
    redirect_to @switch
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/switches_helper.rb
module SwitchesHelper
  def device_state(switch)
    if switch.on?
      'is on!'
    else
      'is off!'
    end
  end

  def checked_box(switch)
    switch.on? ? true : false        
  end

  def find_switch(switch)
    Wemote::Switch.find(switch.name)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wewmo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/switches/edit.html.erb
<h2>Switch (<%= @switch.name %>)</h2>

State: <%= find_switch(@switch).on? ? 'on' : 'off' %>

<%= link_to 'toggle state', switch_path %>

app/views/switches/index.html.erb
<h1>Switch Names</h1>

<ol>
<% @switches.each do |s| %>
  <li>
    <%= link_to s.name, s %> is <%= find_switch(s).on? ? 'on' : 'off' %>
  </li>
<% end %>
</ol>

app/views/switches/show.html.erb
<h2>Switch (<%= @switch.name %>)</h2>

State: <%= find_switch(@switch).on? ? 'on' : 'off' %>


<p><%= link_to 'toggle state', toggle_path(switch: @switch.id) %></p>
<p><%= link_to 'Switches', switches_path %></p>